const array=[
        {
            id:1,
            title:'title',
            img:'ss',
            category:'python',
            youtube:'link',
            github:'Link',
        },
        {
            id:2,
            title:'title',
            img:'ss',
            category:'python',
            youtube:'link',
            github:'Link',
        },
        {
            id:3,
            title:'title',
            img:'ss',
            category:'python',
            youtube:'link',
            github:'Link',
        },
        {
            id:4,
            title:'title',
            img:'ss',
            category:'javascript',
            youtube:'link',
            github:'Link',
        },
        {
            id:5,
            title:'title',
            img:'ss',
            category:'react',
            youtube:'link',
            github:'Link',
        },
        {
            id:6,
            title:'title',
            img:'ss',
            category:'react',
            youtube:'link',
            github:'Link',
        },
        {
            id:7,
            title:'title',
            img:'ss',
            category:'angular',
            youtube:'link',
            github:'Link',
        }
    ];
export default array;
